# Generated by Django 4.2.5 on 2023-10-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id_equipamento', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('provider', models.TextField(max_length=255)),
                ('contato', models.TextField(max_length=255)),
                ('status', models.TextField(max_length=255)),
                ('comentario', models.TextField(max_length=255)),
                ('descricao', models.TextField(max_length=255)),
                ('prof', models.TextField(max_length=255)),
            ],
        ),
    ]
