# Generated by Django 4.2.5 on 2023-10-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='tipo',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
