# Generated by Django 4.2.5 on 2023-10-27 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_alter_equipamento_comentario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipamento',
        ),
    ]
