# Generated by Django 4.2.5 on 2023-10-29 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0002_tecnico'),
        ('equipamentos', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.tecnico'),
        ),
    ]
