# Generated by Django 4.2.5 on 2023-10-29 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0006_alter_equipamento_tecnico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipamento',
        ),
    ]
