# Generated by Django 4.2.5 on 2023-11-03 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0011_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipamento',
        ),
    ]
