# Generated by Django 4.2.5 on 2023-11-17 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0010_remove_solicitacoes_id_equipamento_and_more'),
        ('equipamentos', '0013_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipamento',
        ),
    ]
