# Generated by Django 4.2.5 on 2023-12-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0006_alter_tecnico_celular_alter_tecnico_centro_and_more'),
        ('equipamentos', '0018_alter_equipamento_ano_aquisicao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='tecnicos',
            field=models.ManyToManyField(blank=True, null=True, to='administracao.tecnico'),
        ),
    ]
