# Generated by Django 4.2.5 on 2024-02-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0019_alter_equipamento_tecnicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='tem_prova',
            field=models.BooleanField(default=False),
        ),
    ]
