# Generated by Django 4.2.5 on 2024-02-29 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0020_equipamento_tem_prova'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='tem_palestra',
            field=models.BooleanField(default=False),
        ),
    ]
