# Generated by Django 4.2.5 on 2023-09-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_usuario_idade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progrma_pos_graducao',
            fields=[
                ('id_progrma', models.AutoField(primary_key=True, serialize=False)),
                ('nome_programa', models.TextField(max_length=255)),
            ],
        ),
    ]
