# Generated by Django 4.2.5 on 2023-09-27 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_progrma_pos_graducao_programa_pos_graducao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programa_pos_graducao',
            new_name='Programa_pos_graduacao',
        ),
    ]
