# Generated by Django 4.2.5 on 2023-09-28 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_programa_pos_graducao_programa_pos_graduacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programa_pos_graduacao',
            old_name='id_progrma',
            new_name='id_programa',
        ),
    ]
