# Generated by Django 4.2.5 on 2023-10-06 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_programa_pos_graduacao_programaposgraduacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoPosIC',
            fields=[
                ('id_aluno_pos_ic', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='FormInfra',
            fields=[
                ('id_form_infra', models.AutoField(primary_key=True, serialize=False)),
                ('cem_sbc_equip', models.CharField(max_length=255)),
                ('cem_sbc_equip_apoio', models.CharField(max_length=255)),
                ('cem_sa_equip', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='FormTermo',
            fields=[
                ('id_form_termo', models.AutoField(primary_key=True, serialize=False)),
                ('a', models.CharField(max_length=3)),
                ('b', models.CharField(max_length=3)),
                ('c', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='PosDout',
            fields=[
                ('id_pos_dout', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=17)),
                ('email_inst', models.EmailField(max_length=255)),
                ('matricula_ufabc', models.CharField(max_length=10)),
                ('ramal_lab', models.CharField(max_length=10)),
                ('nome_supervisor', models.CharField(max_length=255)),
                ('centro', models.CharField(max_length=10)),
                ('data_pos', models.DateField()),
                ('possui_bolsa', models.CharField(max_length=10)),
                ('programa_pos', models.CharField(max_length=255)),
                ('plano_trabalho', models.TextField(max_length=255)),
                ('declaracao_ciencia_supervisor', models.CharField(max_length=3)),
                ('id_form_infra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.forminfra')),
                ('id_form_termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formtermo')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=17)),
                ('email_inst', models.EmailField(max_length=255)),
                ('matricula_siape', models.CharField(max_length=10)),
                ('ramal_lab', models.CharField(max_length=10)),
                ('centro', models.CharField(max_length=10)),
                ('programa_pos', models.CharField(max_length=255)),
                ('possui_projeto', models.CharField(max_length=3)),
                ('info_projeto', models.TextField(max_length=255)),
                ('lista_publi', models.TextField(max_length=255)),
                ('id_form_infra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.forminfra')),
                ('id_form_termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formtermo')),
            ],
        ),
    ]
