# Generated by Django 4.2.5 on 2023-10-24 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alunoposic_forminfra_formtermo_posdout_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='id_form_infra',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='id_form_termo',
        ),
    ]
