# Generated by Django 4.2.5 on 2023-10-24 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_docente_id_form_infra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='preCadDocente',
            fields=[
                ('id_pre_cad_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=17)),
                ('email_inst', models.EmailField(max_length=255)),
                ('matricula_siape', models.CharField(max_length=10)),
                ('ramal_lab', models.CharField(max_length=10)),
                ('centro', models.CharField(max_length=10)),
                ('programa_pos', models.CharField(max_length=255)),
                ('possui_projeto', models.CharField(max_length=3)),
                ('info_projeto', models.TextField(max_length=255)),
                ('lista_publi', models.TextField(max_length=255)),
            ],
        ),
    ]
