# Generated by Django 4.2.5 on 2023-10-24 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_precaddocente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formtermo',
            old_name='a',
            new_name='veracidade1',
        ),
        migrations.RenameField(
            model_name='formtermo',
            old_name='b',
            new_name='veracidade2',
        ),
        migrations.RenameField(
            model_name='formtermo',
            old_name='c',
            new_name='veracidade3',
        ),
        migrations.AddField(
            model_name='docente',
            name='id_form_infra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.forminfra'),
        ),
        migrations.AddField(
            model_name='docente',
            name='id_form_termo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.formtermo'),
        ),
    ]
