# Generated by Django 4.2.5 on 2023-10-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_a_formtermo_veracidade1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='preCadPosDout',
            fields=[
                ('id_pre_cad_pos_dout', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=17)),
                ('email_inst', models.EmailField(max_length=255)),
                ('matricula_ufabc', models.CharField(max_length=10)),
                ('ramal_lab', models.CharField(max_length=10)),
                ('nome_supervisor', models.CharField(max_length=255)),
                ('centro', models.CharField(max_length=10)),
                ('data_pos', models.DateField()),
                ('bolsa', models.CharField(max_length=10)),
                ('programa_pos', models.TextField(max_length=255)),
                ('plano_trabalho', models.TextField(max_length=255)),
                ('declaracao_ciencia_supervisor', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='posdout',
            name='programa_pos',
            field=models.TextField(max_length=255),
        ),
    ]
