# Generated by Django 4.2.5 on 2023-10-24 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_precadposdout_alter_posdout_programa_pos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precadposdout',
            old_name='bolsa',
            new_name='possui_bolsa',
        ),
    ]
