# Generated by Django 4.2.5 on 2023-10-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_bolsa_precadposdout_possui_bolsa'),
    ]

    operations = [
        migrations.CreateModel(
            name='preCadAlunoPosIC',
            fields=[
                ('id_pre_cad_aluno_pos_ic', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('celular', models.CharField(default=None, max_length=17)),
                ('email_inst', models.EmailField(max_length=255)),
                ('matricula_ufabc', models.CharField(max_length=10)),
                ('ramal_lab', models.CharField(max_length=10)),
                ('nome_orientador', models.CharField(max_length=255)),
                ('departamento', models.TextField(max_length=255)),
                ('centro', models.CharField(max_length=10)),
                ('data_pos', models.DateField()),
                ('possui_bolsa', models.CharField(max_length=10)),
                ('programa_pos', models.TextField(max_length=255)),
                ('plano_trabalho', models.TextField(max_length=255)),
                ('declaracao_ciencia_orientador', models.CharField(max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='AlunoPosIC',
        ),
    ]
