# Generated by Django 4.2.5 on 2023-10-24 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_precadalunoposic_delete_alunoposic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlunoPosIC',
            fields=[
                ('id_aluno_pos_ic', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=17)),
                ('email_inst', models.EmailField(max_length=255)),
                ('matricula_ufabc', models.CharField(max_length=10)),
                ('ramal_lab', models.CharField(max_length=10)),
                ('nome_orientador', models.CharField(max_length=255)),
                ('departamento', models.CharField(max_length=255)),
                ('centro', models.CharField(max_length=10)),
                ('data_pos', models.DateField()),
                ('possui_bolsa', models.CharField(max_length=10)),
                ('programa_pos', models.TextField(max_length=255)),
                ('plano_trabalho', models.TextField(max_length=255)),
                ('declaracao_ciencia_orientador', models.CharField(max_length=3)),
                ('id_form_infra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.forminfra')),
                ('id_form_termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formtermo')),
            ],
        ),
    ]
