# Generated by Django 4.2.5 on 2023-10-25 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alunoposic'),
    ]

    operations = [
        migrations.CreateModel(
            name='preCadUserExterno',
            fields=[
                ('id_pre_cad_user_externo', models.AutoField(primary_key=True, serialize=False)),
                ('arquivo', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
