# Generated by Django 4.2.5 on 2023-10-25 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_precaduserexterno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='preCadUserExterno',
        ),
    ]
