# Generated by Django 4.2.5 on 2023-10-25 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_delete_precaduserexterno'),
    ]

    operations = [
        migrations.CreateModel(
            name='preCadUserExterno',
            fields=[
                ('id_pre_cad_user_externo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('instituicao', models.CharField(max_length=100)),
                ('atividade', models.CharField(max_length=150)),
                ('endereco_inst', models.CharField(max_length=150)),
                ('celular', models.CharField(max_length=17)),
                ('email_inst', models.EmailField(max_length=200)),
                ('telefone_sala', models.CharField(max_length=200)),
                ('formacao', models.CharField(max_length=200)),
                ('classificacao', models.CharField(max_length=100)),
                ('nome_centro_docente', models.CharField(max_length=150)),
                ('possui_projeto', models.CharField(max_length=3)),
                ('arquivo', models.FileField(upload_to='uploads/')),
                ('infos_projeto', models.TextField(max_length=200)),
                ('publicacoes', models.TextField(max_length=255)),
                ('plano_trabalho', models.TextField(max_length=255)),
                ('manifesto_apoio', models.CharField(max_length=3)),
            ],
        ),
    ]
