# Generated by Django 4.2.5 on 2023-10-25 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_precaduserexterno'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExterno',
            fields=[
                ('id_user_externo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('instituicao', models.CharField(max_length=100)),
                ('atividade', models.CharField(max_length=150)),
                ('endereco_inst', models.CharField(max_length=150)),
                ('celular', models.CharField(max_length=17)),
                ('email_inst', models.EmailField(max_length=200)),
                ('telefone_sala', models.CharField(max_length=200)),
                ('formacao', models.CharField(max_length=200)),
                ('classificacao', models.CharField(max_length=100)),
                ('nome_centro_docente', models.CharField(max_length=150)),
                ('possui_projeto', models.CharField(max_length=3)),
                ('arquivo', models.FileField(upload_to='uploads/')),
                ('infos_projeto', models.TextField(max_length=200)),
                ('publicacoes', models.TextField(max_length=255)),
                ('plano_trabalho', models.TextField(max_length=255)),
                ('manifesto_apoio', models.CharField(max_length=3)),
                ('id_form_infra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.forminfra')),
                ('id_form_termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formtermo')),
            ],
        ),
    ]
