# Generated by Django 4.2.5 on 2023-10-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_userexterno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunoposic',
            name='email_inst',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='email_inst',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='posdout',
            name='email_inst',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='precaduserexterno',
            name='email_inst',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='userexterno',
            name='email_inst',
            field=models.EmailField(max_length=200, unique=True),
        ),
    ]
