# Generated by Django 4.2.5 on 2023-10-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_alunoposic_email_inst_alter_docente_email_inst_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precaduserexterno',
            name='email_inst',
            field=models.EmailField(max_length=200),
        ),
    ]
