# Generated by Django 4.2.5 on 2023-10-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_precaduserexterno_email_inst'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Docente',
        ),
    ]
