# Generated by Django 4.2.5 on 2023-10-25 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_delete_docente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id_docente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=17)),
                ('email_inst', models.EmailField(max_length=255, unique=True)),
                ('matricula_siape', models.CharField(max_length=10)),
                ('ramal_lab', models.CharField(max_length=10)),
                ('centro', models.CharField(max_length=10)),
                ('programa_pos', models.CharField(max_length=255)),
                ('possui_projeto', models.CharField(max_length=3)),
                ('info_projeto', models.TextField(max_length=255)),
                ('lista_publi', models.TextField(max_length=255)),
                ('id_form_infra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.forminfra')),
                ('id_form_termo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.formtermo')),
            ],
        ),
    ]
