# Generated by Django 4.2.5 on 2023-10-26 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunoposic',
            name='id_form_infra',
        ),
        migrations.RemoveField(
            model_name='alunoposic',
            name='id_form_termo',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='id_form_infra',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='id_form_termo',
        ),
        migrations.RemoveField(
            model_name='posdout',
            name='id_form_infra',
        ),
        migrations.RemoveField(
            model_name='posdout',
            name='id_form_termo',
        ),
        migrations.DeleteModel(
            name='preCadAlunoPosIC',
        ),
        migrations.DeleteModel(
            name='preCadDocente',
        ),
        migrations.DeleteModel(
            name='preCadPosDout',
        ),
        migrations.DeleteModel(
            name='preCadUserExterno',
        ),
        migrations.RemoveField(
            model_name='userexterno',
            name='id_form_infra',
        ),
        migrations.RemoveField(
            model_name='userexterno',
            name='id_form_termo',
        ),
        migrations.DeleteModel(
            name='AlunoPosIC',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='PosDout',
        ),
        migrations.DeleteModel(
            name='UserExterno',
        ),
    ]
