# Generated by Django 4.2.5 on 2023-11-01 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_userexterno_posdout_docente_alunoposic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunoposic',
            name='id_form_infra',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='id_form_infra',
        ),
        migrations.RemoveField(
            model_name='posdout',
            name='id_form_infra',
        ),
        migrations.RemoveField(
            model_name='userexterno',
            name='id_form_infra',
        ),
        migrations.DeleteModel(
            name='FormInfra',
        ),
    ]
