# Generated by Django 4.2.5 on 2023-12-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0015_remove_solicitacoes_id_alunoposic_and_more'),
        ('core', '0029_remove_alunoposic_id_form_infra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunoposic',
            name='id_form_termo',
        ),
        migrations.DeleteModel(
            name='preCadAlunoPosIC',
        ),
        migrations.DeleteModel(
            name='AlunoPosIC',
        ),
    ]
