# Generated by Django 4.2.5 on 2023-12-03 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_remove_alunoposic_id_form_termo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='preCadAlunoPosIC',
            fields=[
                ('id_pre_cad_aluno_pos_ic', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=17)),
                ('email_inst', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=50)),
                ('matricula_ufabc', models.CharField(max_length=10)),
                ('ramal_lab', models.CharField(max_length=10)),
                ('nome_orientador', models.CharField(max_length=255)),
                ('perfil', models.CharField(max_length=30)),
                ('data_pos', models.DateField()),
                ('centro', models.CharField(max_length=10)),
                ('bolsa', models.CharField(max_length=10)),
                ('programa_pos', models.TextField(max_length=255)),
                ('plano_trabalho', models.TextField(max_length=255)),
                ('declaracao_ciencia_orientador', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='AlunoPosIC',
            fields=[
                ('id_aluno_pos_ic', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=17)),
                ('email_inst', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=50)),
                ('matricula_ufabc', models.CharField(max_length=10)),
                ('ramal_lab', models.CharField(max_length=10)),
                ('nome_orientador', models.CharField(max_length=255)),
                ('perfil', models.CharField(max_length=30)),
                ('data_pos', models.DateField()),
                ('centro', models.CharField(max_length=10)),
                ('bolsa', models.CharField(max_length=10)),
                ('programa_pos', models.TextField(max_length=255)),
                ('plano_trabalho', models.TextField(max_length=255)),
                ('declaracao_ciencia_orientador', models.CharField(max_length=3)),
                ('id_form_termo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formtermo')),
            ],
        ),
    ]
