# Generated by Django 4.2.5 on 2023-12-03 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_precadalunoposic_alunoposic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunoposic',
            name='programa_pos',
        ),
        migrations.RemoveField(
            model_name='precadalunoposic',
            name='programa_pos',
        ),
    ]
