# Generated by Django 4.2.5 on 2023-12-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_alunoposic_programa_pos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunoposic',
            name='email_inst',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='precadalunoposic',
            name='email_inst',
            field=models.EmailField(max_length=255),
        ),
    ]
