# Generated by Django 4.2.5 on 2023-12-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_alunoposic_email_inst_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='precadposdout',
            old_name='possui_bolsa',
            new_name='bolsa',
        ),
        migrations.RemoveField(
            model_name='precadposdout',
            name='programa_pos',
        ),
        migrations.AddField(
            model_name='precadposdout',
            name='perfil',
            field=models.CharField(default='valor_padrao', max_length=30),
        ),
        migrations.AlterField(
            model_name='alunoposic',
            name='perfil',
            field=models.CharField(default='valor_padrao', max_length=30),
        ),
    ]
