# Generated by Django 4.2.5 on 2023-12-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_rename_possui_bolsa_precadposdout_bolsa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunoposic',
            name='perfil',
            field=models.CharField(max_length=30),
        ),
    ]
