# Generated by Django 4.2.5 on 2023-12-03 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_alunoposic_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precadposdout',
            name='perfil',
            field=models.CharField(max_length=30),
        ),
    ]
