# Generated by Django 4.2.5 on 2023-12-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_precadposdout_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunoposic',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='posdout',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='precadalunoposic',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='precaddocente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='precadposdout',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='precaduserexterno',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='userexterno',
            name='nome',
        ),
        migrations.AddField(
            model_name='alunoposic',
            name='primeiro_nome',
            field=models.CharField(default='first', max_length=255),
        ),
        migrations.AddField(
            model_name='alunoposic',
            name='segundo_nome',
            field=models.CharField(default='nome', max_length=255),
        ),
        migrations.AddField(
            model_name='docente',
            name='primeiro_nome',
            field=models.CharField(default='first', max_length=255),
        ),
        migrations.AddField(
            model_name='docente',
            name='segundo_nome',
            field=models.CharField(default='nome', max_length=255),
        ),
        migrations.AddField(
            model_name='posdout',
            name='primeiro_nome',
            field=models.CharField(default='first', max_length=255),
        ),
        migrations.AddField(
            model_name='posdout',
            name='segundo_nome',
            field=models.CharField(default='nome', max_length=255),
        ),
        migrations.AddField(
            model_name='precadalunoposic',
            name='primeiro_nome',
            field=models.CharField(default='first', max_length=255),
        ),
        migrations.AddField(
            model_name='precadalunoposic',
            name='segundo_nome',
            field=models.CharField(default='nome', max_length=255),
        ),
        migrations.AddField(
            model_name='precaddocente',
            name='primeiro_nome',
            field=models.CharField(default='first', max_length=255),
        ),
        migrations.AddField(
            model_name='precaddocente',
            name='segundo_nome',
            field=models.CharField(default='nome', max_length=255),
        ),
        migrations.AddField(
            model_name='precadposdout',
            name='primeiro_nome',
            field=models.CharField(default='first', max_length=255),
        ),
        migrations.AddField(
            model_name='precadposdout',
            name='segundo_nome',
            field=models.CharField(default='nome', max_length=255),
        ),
        migrations.AddField(
            model_name='precaduserexterno',
            name='primeiro_nome',
            field=models.CharField(default='first', max_length=255),
        ),
        migrations.AddField(
            model_name='precaduserexterno',
            name='segundo_nome',
            field=models.CharField(default='nome', max_length=255),
        ),
        migrations.AddField(
            model_name='userexterno',
            name='primeiro_nome',
            field=models.CharField(default='first', max_length=255),
        ),
        migrations.AddField(
            model_name='userexterno',
            name='segundo_nome',
            field=models.CharField(default='nome', max_length=255),
        ),
    ]
