# Generated by Django 4.2.5 on 2023-12-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_alunoposic_nome_remove_docente_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunoposic',
            name='primeiro_nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='alunoposic',
            name='segundo_nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='docente',
            name='primeiro_nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='docente',
            name='segundo_nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='posdout',
            name='primeiro_nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='posdout',
            name='segundo_nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='precadalunoposic',
            name='primeiro_nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='precadalunoposic',
            name='segundo_nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='precaddocente',
            name='primeiro_nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='precaddocente',
            name='segundo_nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='precadposdout',
            name='primeiro_nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='precadposdout',
            name='segundo_nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='precaduserexterno',
            name='primeiro_nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='precaduserexterno',
            name='segundo_nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userexterno',
            name='primeiro_nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userexterno',
            name='segundo_nome',
            field=models.CharField(max_length=255),
        ),
    ]
