# Generated by Django 4.2.5 on 2023-12-04 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_alunoposic_primeiro_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id_login', models.AutoField(primary_key=True, serialize=False)),
                ('email_inst', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=50)),
                ('password_change_required', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='alunoposic',
            name='email_inst',
        ),
        migrations.RemoveField(
            model_name='alunoposic',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='email_inst',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='userexterno',
            name='email_inst',
        ),
        migrations.RemoveField(
            model_name='userexterno',
            name='senha',
        ),
        migrations.AddField(
            model_name='alunoposic',
            name='user',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.login'),
        ),
        migrations.AddField(
            model_name='docente',
            name='user',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.login'),
        ),
        migrations.AddField(
            model_name='userexterno',
            name='user',
            field=models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, to='core.login'),
        ),
    ]
