# Generated by Django 4.2.5 on 2023-12-04 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_alunoposic_user_alter_docente_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunoposic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userexterno',
            name='user',
        ),
    ]
