# Generated by Django 4.2.5 on 2023-12-04 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='user',
        ),
    ]
