# Generated by Django 4.2.5 on 2023-12-04 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_remove_docente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunoposic',
            name='id_login',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.login'),
        ),
        migrations.AddField(
            model_name='docente',
            name='id_login',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.login'),
        ),
        migrations.AddField(
            model_name='userexterno',
            name='id_login',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.login'),
        ),
    ]
