# Generated by Django 4.2.5 on 2023-12-04 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_alunoposic_id_login_docente_id_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='precadalunoposic',
            name='id_login',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.login'),
        ),
        migrations.AddField(
            model_name='precaddocente',
            name='id_login',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.login'),
        ),
        migrations.AddField(
            model_name='precaduserexterno',
            name='id_login',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.login'),
        ),
    ]
