# Generated by Django 4.2.5 on 2023-12-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_precadalunoposic_id_login_precaddocente_id_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='perfil',
            field=models.CharField(default='perfil', max_length=30),
        ),
    ]
