# Generated by Django 4.2.5 on 2023-12-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_login_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='preLogin',
            fields=[
                ('id_pre_login', models.AutoField(primary_key=True, serialize=False)),
                ('email_inst', models.EmailField(max_length=255, unique=True)),
                ('senha', models.CharField(max_length=50)),
                ('perfil', models.CharField(default='perfil', max_length=30)),
                ('password_change_required', models.BooleanField(default=True)),
            ],
        ),
    ]
