# Generated by Django 4.2.5 on 2023-12-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_prelogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='email_inst',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prelogin',
            name='email_inst',
            field=models.EmailField(max_length=255),
        ),
    ]
