# Generated by Django 4.2.5 on 2023-12-04 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_alter_login_email_inst_alter_prelogin_email_inst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precadalunoposic',
            name='id_login',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.prelogin'),
        ),
        migrations.AlterField(
            model_name='precaddocente',
            name='id_login',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.prelogin'),
        ),
        migrations.AlterField(
            model_name='precaduserexterno',
            name='id_login',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.prelogin'),
        ),
    ]
