# Generated by Django 4.2.5 on 2023-12-04 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_alter_precadalunoposic_id_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='programa_pos',
        ),
    ]
