# Generated by Django 4.2.5 on 2023-12-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_remove_docente_programa_pos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunoposic',
            name='email_inst',
        ),
        migrations.RemoveField(
            model_name='alunoposic',
            name='senha',
        ),
    ]
