# Generated by Django 4.2.5 on 2023-12-04 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_alunoposic_id_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunoposic',
            name='id_docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.docente'),
        ),
    ]
