# Generated by Django 4.2.5 on 2023-12-06 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0019_remove_solicitacoes_id_posdout_and_more'),
        ('core', '0058_alter_alunoposic_id_docente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posdout',
            name='id_form_termo',
        ),
        migrations.DeleteModel(
            name='preCadPosDout',
        ),
        migrations.DeleteModel(
            name='PosDout',
        ),
    ]
