# Generated by Django 4.2.5 on 2023-12-10 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_login_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='data_cadastro',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='login',
            name='data_ultimo_login',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 1, 1, 0, 0), null=True),
        ),
    ]
