# Generated by Django 4.2.5 on 2023-12-11 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_login_data_cadastro_login_data_ultimo_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunoposic',
            name='bolsa',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='alunoposic',
            name='centro',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='alunoposic',
            name='matricula_ufabc',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='alunoposic',
            name='ramal_lab',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='docente',
            name='centro',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='docente',
            name='matricula_siape',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='docente',
            name='ramal_lab',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='precaddocente',
            name='centro',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='precaddocente',
            name='matricula_siape',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='precaddocente',
            name='ramal_lab',
            field=models.CharField(max_length=30),
        ),
    ]
