# Generated by Django 4.2.5 on 2024-01-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_alunoposic_bolsa_alter_alunoposic_centro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunoposic',
            name='plano_trabalho',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='precadalunoposic',
            name='plano_trabalho',
            field=models.TextField(),
        ),
    ]
