# Generated by Django 4.2.5 on 2023-12-06 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_remove_posdout_id_form_termo_delete_precadposdout_and_more'),
        ('administracao', '0004_tecnico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tecnico',
            name='divisao',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='email',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='tecnico',
            name='senha',
        ),
        migrations.AddField(
            model_name='tecnico',
            name='celular',
            field=models.CharField(default=0, max_length=17),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='centro',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='id_form_termo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.formtermo'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='id_login',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.login'),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='info_projeto',
            field=models.TextField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='lista_publi',
            field=models.TextField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='matricula_siape',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='possui_projeto',
            field=models.CharField(default=0, max_length=3),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='primeiro_nome',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='ramal_lab',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='tecnico',
            name='segundo_nome',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.CreateModel(
            name='preCadTecnico',
            fields=[
                ('id_pre_cad_tecnico', models.AutoField(primary_key=True, serialize=False)),
                ('primeiro_nome', models.CharField(max_length=255)),
                ('segundo_nome', models.CharField(max_length=255)),
                ('celular', models.CharField(max_length=17)),
                ('email_inst', models.EmailField(max_length=255)),
                ('senha', models.CharField(max_length=50)),
                ('matricula_siape', models.CharField(max_length=10)),
                ('ramal_lab', models.CharField(max_length=10)),
                ('centro', models.CharField(max_length=10)),
                ('programa_pos', models.CharField(max_length=255)),
                ('possui_projeto', models.CharField(max_length=3)),
                ('info_projeto', models.TextField(max_length=255)),
                ('lista_publi', models.TextField(max_length=255)),
                ('id_login', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.prelogin')),
            ],
        ),
    ]
