# Generated by Django 4.2.5 on 2023-12-06 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_remove_posdout_id_form_termo_delete_precadposdout_and_more'),
        ('administracao', '0005_remove_tecnico_divisao_remove_tecnico_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnico',
            name='celular',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='centro',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='id_form_termo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.formtermo'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='info_projeto',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='lista_publi',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='matricula_siape',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='possui_projeto',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='primeiro_nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='ramal_lab',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='segundo_nome',
            field=models.CharField(max_length=255),
        ),
    ]
