# Generated by Django 4.2.5 on 2023-09-20 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_projeto_cem', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
