# Generated by Django 4.2.5 on 2024-01-12 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0002_alter_agendamento_additional_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id_feriado', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FimDeSemana',
            fields=[
                ('id_fim_de_semana', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id_calendario', models.AutoField(primary_key=True, serialize=False)),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('quantidade_dias', models.IntegerField()),
                ('feriados', models.ManyToManyField(blank=True, to='agendamentos.feriado')),
                ('finais_de_semana', models.ManyToManyField(blank=True, null=True, to='agendamentos.fimdesemana')),
            ],
        ),
    ]
