# Generated by Django 4.2.5 on 2024-01-12 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0004_alter_feriado_data_alter_fimdesemana_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FimDeSemana',
            new_name='DiaOff',
        ),
        migrations.RenameField(
            model_name='calendario',
            old_name='finais_de_semana',
            new_name='dia_off',
        ),
        migrations.RenameField(
            model_name='diaoff',
            old_name='id_fim_de_semana',
            new_name='id_dia_off',
        ),
        migrations.RemoveField(
            model_name='calendario',
            name='feriados',
        ),
        migrations.DeleteModel(
            name='Feriado',
        ),
    ]
