# Generated by Django 4.2.5 on 2024-01-16 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0006_remove_calendario_dia_off_diaoff_calendario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaoff',
            name='calendario',
        ),
        migrations.DeleteModel(
            name='Calendario',
        ),
        migrations.DeleteModel(
            name='DiaOff',
        ),
    ]
