# Generated by Django 4.2.5 on 2024-01-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0008_calendario_diaoff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diaoff',
            name='calendario',
        ),
        migrations.AddField(
            model_name='calendario',
            name='dia_off',
            field=models.ManyToManyField(blank=True, null=True, to='agendamentos.diaoff'),
        ),
    ]
