# Generated by Django 4.2.5 on 2024-01-18 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0010_dias_calendario_dia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendario',
            old_name='dia',
            new_name='dias',
        ),
        migrations.RenameField(
            model_name='calendario',
            old_name='dia_off',
            new_name='dias_off',
        ),
    ]
