# Generated by Django 4.2.5 on 2024-01-19 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0011_rename_dia_calendario_dias_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('dia_da_semana', models.CharField(max_length=20)),
                ('feriado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Calendario',
        ),
        migrations.DeleteModel(
            name='DiaOff',
        ),
        migrations.DeleteModel(
            name='Dias',
        ),
        migrations.AddField(
            model_name='dia',
            name='mes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.mes'),
        ),
    ]
