# Generated by Django 4.2.5 on 2024-01-19 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0012_dia_mes_delete_calendario_delete_diaoff_delete_dias_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dia',
        ),
        migrations.DeleteModel(
            name='Mes',
        ),
    ]
