# Generated by Django 4.2.5 on 2024-01-19 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0013_delete_dia_delete_mes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mes',
            fields=[
                ('id_mes', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id_dia', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('dia_da_semana', models.CharField(max_length=20)),
                ('feriado', models.BooleanField(default=False)),
                ('mes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.mes')),
            ],
        ),
    ]
