# Generated by Django 4.2.5 on 2024-01-29 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0015_alter_agendamento_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='mes',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
