# Generated by Django 4.2.5 on 2024-01-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0018_alter_mes_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dia',
            name='numero',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
