# Generated by Django 4.2.5 on 2024-03-26 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0021_equipamento_tem_palestra'),
        ('agendamentos', '0021_alter_agendamento_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraAgendamento',
            fields=[
                ('id_regra_agendamento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_regra', models.CharField(max_length=250)),
                ('parametros', models.JSONField()),
                ('descricao', models.TextField()),
                ('equipamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.equipamento')),
            ],
        ),
    ]
