# Generated by Django 4.2.5 on 2024-03-28 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0022_regraagendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='cancelado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='nome_orientador',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='nome_usuario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
