# Generated by Django 4.2.5 on 2024-03-28 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0023_agendamento_cancelado_agendamento_nome_orientador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='cancelado',
        ),
    ]
