# Generated by Django 4.2.5 on 2023-09-28 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_id_progrma_programa_pos_graduacao_id_programa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Programa_pos_graduacao',
            new_name='ProgramaPosGraduacao',
        ),
    ]
