# Generated by Django 4.2.5 on 2023-11-05 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0029_remove_alunoposic_id_form_infra_and_more'),
        ('equipamentos', '0013_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacoes',
            fields=[
                ('id_solicitacao', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('status', models.CharField(max_length=50)),
                ('id_AlunoPosIC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.alunoposic')),
                ('id_Docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.docente')),
                ('id_PosDout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.posdout')),
                ('id_UserExterno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.userexterno')),
                ('id_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.equipamento')),
            ],
        ),
    ]
