# Generated by Django 4.2.5 on 2023-11-16 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0002_treinamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Treinamento',
        ),
    ]
