# Generated by Django 4.2.5 on 2023-11-16 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0004_treinamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Treinamento',
        ),
    ]
