# Generated by Django 4.2.5 on 2023-11-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0006_treinamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamento',
            name='compareceu',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='justificativa',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
