# Generated by Django 4.2.5 on 2023-11-16 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0007_alter_treinamento_compareceu_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Treinamento',
        ),
    ]
