# Generated by Django 4.2.5 on 2023-11-17 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0009_treinamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacoes',
            name='id_equipamento',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='id_equipamento',
        ),
    ]
