# Generated by Django 4.2.5 on 2023-11-17 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0010_remove_solicitacoes_id_equipamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treinamento',
            name='id_AlunoPosIC',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='id_Docente',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='id_PosDout',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='id_UserExterno',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='id_solicitacao',
        ),
        migrations.DeleteModel(
            name='Solicitacoes',
        ),
        migrations.DeleteModel(
            name='Treinamento',
        ),
    ]
