# Generated by Django 4.2.5 on 2023-11-19 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0012_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Treinamento',
        ),
    ]
