# Generated by Django 4.2.5 on 2023-12-03 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_precadalunoposic_alunoposic'),
        ('treinamento', '0015_remove_solicitacoes_id_alunoposic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacoes',
            name='id_AlunoPosIC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.alunoposic'),
        ),
        migrations.AddField(
            model_name='treinamento',
            name='id_AlunoPosIC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.alunoposic'),
        ),
    ]
