# Generated by Django 4.2.5 on 2023-12-04 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0016_solicitacoes_id_alunoposic_treinamento_id_alunoposic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treinamento',
            name='id_AlunoPosIC',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='id_Docente',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='id_PosDout',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='id_UserExterno',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='id_equipamento',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='id_solicitacao',
        ),
        migrations.DeleteModel(
            name='Solicitacoes',
        ),
        migrations.DeleteModel(
            name='Treinamento',
        ),
    ]
