# Generated by Django 4.2.5 on 2023-12-11 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_alunoposic_bolsa_alter_alunoposic_centro_and_more'),
        ('treinamento', '0019_remove_solicitacoes_id_posdout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacoes',
            name='id_AlunoPosIC',
        ),
        migrations.RemoveField(
            model_name='solicitacoes',
            name='id_Docente',
        ),
        migrations.RemoveField(
            model_name='solicitacoes',
            name='id_UserExterno',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='id_AlunoPosIC',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='id_Docente',
        ),
        migrations.RemoveField(
            model_name='treinamento',
            name='id_UserExterno',
        ),
        migrations.AddField(
            model_name='solicitacoes',
            name='id_login',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.login'),
        ),
        migrations.AddField(
            model_name='treinamento',
            name='id_login',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.login'),
        ),
    ]
