# Generated by Django 4.2.5 on 2023-12-17 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0007_remove_precadtecnico_info_projeto_and_more'),
        ('treinamento', '0021_treinamento_id_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamento',
            name='id_tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.tecnico'),
        ),
    ]
