# Generated by Django 4.2.5 on 2023-12-17 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_alunoposic_bolsa_alter_alunoposic_centro_and_more'),
        ('treinamento', '0022_alter_treinamento_id_tecnico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treinamento',
            name='id_tecnico',
        ),
        migrations.AddField(
            model_name='treinamento',
            name='id_login_tecnico',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='login_tecnico', to='core.login'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='id_login',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_usuario', to='core.login'),
        ),
    ]
