# Generated by Django 4.2.5 on 2023-12-17 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_alter_alunoposic_bolsa_alter_alunoposic_centro_and_more'),
        ('treinamento', '0023_remove_treinamento_id_tecnico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamento',
            name='id_login_tecnico',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='login_tecnico', to='core.login'),
        ),
    ]
