# Generated by Django 4.2.5 on 2023-12-21 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0007_remove_precadtecnico_info_projeto_and_more'),
        ('treinamento', '0027_alter_treinamento_id_login_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamento',
            name='id_login_tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_tecnico', to='administracao.tecnico'),
        ),
    ]
