# Generated by Django 4.2.5 on 2023-12-21 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracao', '0007_remove_precadtecnico_info_projeto_and_more'),
        ('core', '0062_alter_alunoposic_bolsa_alter_alunoposic_centro_and_more'),
        ('treinamento', '0028_alter_treinamento_id_login_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treinamento',
            name='id_login',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.login'),
        ),
        migrations.AlterField(
            model_name='treinamento',
            name='id_login_tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.tecnico'),
        ),
    ]
