# Generated by Django 4.2.5 on 2024-02-21 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0029_alter_treinamento_id_login_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treinamento',
            old_name='id_login',
            new_name='id_login_usuario',
        ),
    ]
