# Generated by Django 4.2.5 on 2024-02-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0033_rename_id_login_tecnico_treinamento_id_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prova',
            name='aptidao',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
