# Generated by Django 4.2.5 on 2024-02-29 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0020_equipamento_tem_prova'),
        ('administracao', '0007_remove_precadtecnico_info_projeto_and_more'),
        ('core', '0063_alter_alunoposic_plano_trabalho_and_more'),
        ('treinamento', '0034_alter_prova_aptidao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Palestra',
            fields=[
                ('id_palestra', models.AutoField(primary_key=True, serialize=False)),
                ('data_palestra', models.DateField()),
                ('hora_inicio_palestra', models.TimeField()),
                ('hora_termino_palestra', models.TimeField()),
                ('local_palestra', models.CharField(max_length=50)),
                ('compareceu', models.CharField(blank=True, max_length=5, null=True)),
                ('justificativa', models.CharField(blank=True, max_length=225, null=True)),
                ('aptidao', models.CharField(blank=True, max_length=10, null=True)),
                ('id_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.equipamento')),
                ('id_login_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.login')),
                ('id_solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinamento.solicitacoes')),
                ('id_tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracao.tecnico')),
            ],
        ),
    ]
