# Generated by Django 4.2.5 on 2024-03-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0035_palestra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='palestra',
            old_name='data_palestra',
            new_name='data_inicio_palestra',
        ),
        migrations.RenameField(
            model_name='prova',
            old_name='data_prova',
            new_name='data_inicio_prova',
        ),
        migrations.AddField(
            model_name='palestra',
            name='data_termino_palestra',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='prova',
            name='data_termino_prova',
            field=models.DateField(null=True),
        ),
    ]
