# Generated by Django 4.2.5 on 2024-03-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treinamento', '0036_rename_data_palestra_palestra_data_inicio_palestra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prova',
            name='info_adicional',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='treinamento',
            name='info_adicional',
            field=models.TextField(null=True),
        ),
    ]
